controllers/UserController.php
<?php

class UserController extends Controller
{
	/**
	 * @var mixed tooltip for the permission menagement
	 */
	public static $_permissionControl = array(
					'write'=>'can invite other users.',
					'admin'=>'can edit other users, ban them and approve their registrations.',
					);
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'userGroupsAccessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // just guest can perform 'activate', 'login' and 'passRequest' actions
				'actions'=>array('activate','login', 'passRequest'),
				'ajax'=>false,
				'users'=>array('?'),
			),
			array('allow',  // captchas can be loaded just by guests
				'actions'=>array('captcha'),
				'expression'=>'UserGroupsConfiguration::findRule("registration")',
				'users'=>array('?'),
			),
			array('allow',  // just guest can perform registration actions and just if it is enabled
				'actions'=>array('register'),
				'ajax'=>false,
				'expression'=>'UserGroupsConfiguration::findRule("registration")',
				'users'=>array('?'),
			),
			array('allow',  // actions users can access while in recovery mode
				'actions'=>array('recovery','logout'),
				'users'=>array('#'),
			),
			array('allow', // allow authenticated user to perform 'logout' actions
				'actions'=>array('logout'),
				'users'=>array('@'),
			),
			array('allow',  // allow logged user to access the userlist page if the have admin rights on users or if the list is public
				'actions'=>array('index'),
				'expression'=>'UserGroupsConfiguration::findRule("public_user_list") || Yii::app()->user->pbac("userGroups.user.admin")',
				'users'=>array('@'),
			),
			array('allow',  // allow guest to view users profiles according to the configuration
				'actions'=>array('view'),
				'expression'=>'UserGroupsConfiguration::findRule("public_profiles")',
				'users'=>array('?','@'),
			),
			array('allow',  // allow logged user to view other users profiles according to the configuration and always their own
				'actions'=>array('view'),
				'expression'=>'UserGroupsConfiguration::findRule("profile_privacy") || strtolower(Yii::app()->user->name) === (isset($_GET["u"]) ? strtolower($_GET["u"]) : strtolower(Yii::app()->user->name))',
				'users'=>array('@'),
			),
			array('allow',  // allow user with user admin permission to view every profile, approve, ban and invite users
				'actions'=>array('invite'),
				'pbac'=>array('write'),
			),
			array('allow',  // allow user with user admin permission to view every profile, approve, ban and invite users
				'actions'=>array('view', 'approve', 'ban', 'invite'),
				'pbac'=>array('admin', 'admin.admin'),
			),
			array('allow',  // allow a user tu open an update view just on their own accounts
				'actions'=>array('update'),
				'expression'=>'$_GET["id"] == Yii::app()->user->id',
				'ajax'=>true,
			),
			array('allow', // allow user with admin permission to perform any action
				'pbac'=>array('admin', 'admin.admin'),
				'ajax'=>true,
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * override of the actions method to implement captcha
	 */
	public function actions()
	{
		return array(
		// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
		);
	}

	/**
	 * Lists all users.
	 */
	public function actionIndex()
	{
		$model=new UserGroupsUser('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['UserGroupsUser']))
			$model->attributes=$_GET['UserGroupsUser'];

		if (Yii::app()->request->isAjaxRequest)
			$this->renderPartial('index',array('model'=>$model,), false, true);
		else
			$this->render('index',array('model'=>$model,), false, true);
	}

	/**
	 * render a user profile
	 */
	public function actionView()
	{
		// load the user profile according to the request
		if (isset($_GET['u'])) {
			// look for the right user criteria to use according to the viewer permissions
			if (Yii::app()->user->pbac(array('user.admin', 'admin.admin')))
				$criteria = array('username'=>$_GET['u']);
			else
				$criteria = array('username'=>$_GET['u'],'status'=>UserGroupsUser::ACTIVE);
			// load the profile
			$model=UserGroupsUser::model()->findByAttributes($criteria);
			if($model===null || ($model->relUserGroupsGroup->level > Yii::app()->user->level && !UserGroupsConfiguration::findRule('public_profiles')))
				throw new CHttpException(404,Yii::t('userGroupsModule.general','The requested page does not exist.'));
		} else
			$model=$this->loadModel(Yii::app()->user->id);

		// load the profile extensions
		$profiles = array();
		$profile_list = Yii::app()->controller->module->profile;


		foreach ($profile_list as $p) {
			// check if the profile data exist on the current user, otherwise
			// create an instance of the profile extension
			$relation = "rel$p";

			if (!$model->$relation instanceof CActiveRecord)
				$p_instance = new $p;
			else
				$p_instance = $model->$relation;

			// check if the profile extension is supporting profile views
			$views = $p_instance->profileViews();
			if (isset($views[UserGroupsUser::VIEW])) {
				$profiles[] = array('view' => $views[UserGroupsUser::VIEW], 'model' => $p_instance);
			}
		}


		if (Yii::app()->request->isAjaxRequest || isset($_GET['_isAjax']))
			$this->renderPartial('view', array('model'=>$model, 'profiles' => $profiles), false, true);
		else
			$this->render('view', array('model'=>$model, 'profiles' => $profiles));
	}

	/**
	 * user registration
	 */
	public function actionRegister()
	{
		$model=new UserGroupsUser('registration');

		// set the profile extension array
		$profiles = array();
		$profile_list = Yii::app()->controller->module->profile;

		foreach ($profile_list as $p) {
			// create an instance of the profile extension
			$p_instance = new $p('registration');
			// check if the profile extension is supporting registration
			$views = $p_instance->profileViews();
			if (isset($views[UserGroupsUser::REGISTRATION])) {
				$profiles[] = array('view' => $views[UserGroupsUser::REGISTRATION], 'model' => $p_instance);
			}
		}

		if(isset($_POST['UserGroupsUser']))
		{
			$model->attributes=$_POST['UserGroupsUser'];
			// set validation for additional fields
			foreach ($profiles as &$p) {

				if (isset($_POST[get_class($p['model'])]))
					$p['model']->attributes = $_POST[get_class($p['model'])];

				if (!$p['model']->validate())
					$error = true;
			}
			if ($model->validate() && !isset($error)) {
				if($model->save()) {
					// save the related profile extensions
					foreach ($profiles as $p) {
						$p['model']->ug_id = $model->id;
						$p['model']->save();
					}
					if (UserGroupsConfiguration::findRule('registration_auto_login') === true)
					{
						$model->login('auto');
						$this->redirect(Yii::app()->user->returnUrl);
					}
					$this->redirect(Yii::app()->baseUrl . '/userGroups');
				}
			}
		}

		$this->render('register',array(
			'model'=>$model,
			'profiles' => $profiles,
		));
	}

	/**
	 * user invite form
	 */
	public function actionInvite()
	{
		$model=new UserGroupsUser('invitation');

		$this->performAjaxValidation($model);

		if(isset($_POST['UserGroupsUser']))
		{
			$model->attributes=$_POST['UserGroupsUser'];
			if ($model->validate()) {
				if($model->save()) {
					$mail = new UGMail($model, UGMail::INVITATION);
					$mail->send();
				} else
					Yii::app()->user->setFlash('user', Yii::t('userGroupsModule.general','An Error Occurred. Please try later.'));
				$this->redirect(Yii::app()->baseUrl . '/userGroups');
			}
		}

		if (Yii::app()->request->isAjaxRequest)
			$this->renderPartial('invite',array('model'=>$model,), false, true);
		else
			$this->render('invite',array('model'=>$model,));
	}

	/**
	 * Updates a user data
	 * if the update is successfull the user profile will be reloaded
	 * You can change password or mail indipendently
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$miscModel=$this->loadModel($id, 'changeMisc');
		$passModel= clone $miscModel;
		$passModel->setScenario('changePassword');
		$passModel->password = NULL;

		// pass the models inside the array for ajax validation
		$ajax_validation = array($miscModel, $passModel);

		// load additional profile models
		$profile_models = array();
		$profiles = $this->module->profile;
		foreach ($profiles as $p) {
			$external_profile = new $p;
			// check if the loaded profile has an update view
			$external_profile_views = $external_profile->profileViews();
			if (array_key_exists(UserGroupsUser::EDIT, $external_profile_views)) {
				// load the model data
				$loaded_data = $external_profile->findByAttributes(array('ug_id' => $id));
				$external_profile = $loaded_data ? $loaded_data : $external_profile;
				// set the scenario
				$external_profile->setScenario('updateProfile');
				// load the models inside both the ajax validation array and the profile models
				// array to pass it to the view
				$profile_models[$p] = $external_profile;
				$ajax_validation[] = $external_profile;
			}
		}

		// perform ajax validation
		$this->performAjaxValidation($ajax_validation);

		// check if an additional profile model form was sent
		if ($form = array_intersect_key($_POST, array_flip($profiles))) {
			$model_name = key($form);
			$form_values = reset($form);
			// load the form values into the model

views/admin/accessList.php
<?php $name = (int)$what === UserGroupsAccess::USER ? $data->username : $data->groupname; // assign to name it's value ?>
<h3>
	<?php 
	if ((int)$what === UserGroupsAccess::USER) {
		if ($id === 'new')
			echo Yii::t('userGroupsModule.admin', 'New User: Data and Access Permissions');
		else
			echo Yii::t('userGroupsModule.admin', 'User {username}: Data and Access Permissions', array('{username}' => ucfirst($name)));
	} else {
		if ($id === 'new')
			echo Yii::t('userGroupsModule.admin', 'New Group: Data and Access Permissions');
		else
			echo Yii::t('userGroupsModule.admin', 'Group {groupname}: Data and Access Permissions', array('{groupname}' => ucfirst($name)));
	}
	?>
</h3>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-groups-access-form-' . $what,
	'enableAjaxValidation'=>false,
	'action'=> Yii::app()->baseUrl .'/userGroups/admin',
)); ?>

<?php
$this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$dataProvider,
	'ajaxUpdate'=>false,
	'enableSorting'=>false,
	'summaryText'=>false,
	'id'=>'rule-list',
	'selectableRows'=>0,
	'columns'=>array(
		
		array(
			'name'=>'Module',
		),
		
		array(
			'name'=>'Controller',
		),
		
		array(
			'name'=>'Read',
			'type'=>'raw',
		),
		
		array(
			'name'=>'Write',
			'type'=>'raw',
		),
		
		array(
			'name'=>'Admin',
			'type'=>'raw',
		),
		
	),
));
?>
<?php 
if (Yii::app()->user->pbac('userGroups.admin.admin')) { ?>
	<div class="row">
		<?php 
		if ((int)$what === UserGroupsAccess::GROUP) {
			echo CHtml::label(Yii::t('userGroupsModule.general','Group Level'), 'UserGroupsAccess_'.$what.'_level', array('class'=>'inline')) . CHtml::dropDownList('UserGroupsAccess['.$what.'][level]', $data->level, array_reverse(range(0,Yii::app()->user->level - 1), true));
			echo CHtml::label(Yii::t('userGroupsModule.general','Home'), 'UserGroupsAccess_'.$what.'_home', array('class'=>'inline')) . CHtml::dropDownList('UserGroupsAccess['.$what.'][home]', $data->home, UserGroupsAccess::homeList());
			echo CHtml::label(Yii::t('userGroupsModule.general','Group Name'), 'UserGroupsAccess_'.$what.'_groupname', array('class'=>'inline'));
			echo CHtml::textField('UserGroupsAccess['.$what.'][groupname]', $name);
		}
		if ((int)$what === UserGroupsAccess::USER) {
			echo CHtml::label(Yii::t('userGroupsModule.general','User Name'), 'UserGroupsAccess_'.$what.'_username', array('class'=>'inline'));
			echo CHtml::textField('UserGroupsAccess['.$what.'][username]', $name);
			echo CHtml::label(Yii::t('userGroupsModule.general','Group'), 'UserGroupsAccess_'.$what.'_group_id', array('class'=>'inline')) . CHtml::dropDownList('UserGroupsAccess['.$what.'][group_id]', $data->group_id, UserGroupsGroup::groupList());
			$home_lists = UserGroupsAccess::homeList(); 
			array_unshift($home_lists, Yii::t('userGroupsModule.admin','Group Home: {home}', array('{home}'=>$data->group_home)));
			echo CHtml::label(Yii::t('userGroupsModule.general','Home'), 'UserGroupsAccess_'.$what.'_home', array('class'=>'inline')) . CHtml::dropDownList('UserGroupsAccess['.$what.'][home]', $data->home, $home_lists); 
			echo CHtml::label(Yii::t('userGroupsModule.general','Email'), 'UserGroupsAccess_'.$what.'_email', array('class'=>'inline')) . CHtml::textField('UserGroupsAccess['.$what.'][email]', $data->email);
		}
		?>
	</div>
	<?php if ($id === 'new' && (int)$what === UserGroupsAccess::USER) { ?>
	<div class="row">
		<?php echo CHtml::label(Yii::t('userGroupsModule.general','Password'), 'UserGroupsAccess_'.$what.'_password', array('class'=>'inline')); ?>
		<?php echo CHtml::textField('UserGroupsAccess['.$what.'][password]', $data->password); ?>
	</div>
	<div class="row">
		<p><?php echo Yii::t('userGroupsModule.admin','if you omit the password a random one will be generated'); ?></p>
		<p><?php echo Yii::t('userGroupsModule.admin','if you omit the username the user will be able to chose one upon activation of the account'); ?></p>
	</div>
	<?php } ?>
<?php } ?>

<div class="row buttons left-floated">
	<?php echo CHtml::hiddenField('UserGroupsAccess[what]', $what); ?>
	<?php echo CHtml::hiddenField('UserGroupsAccess[id]', $id); ?>
	<?php echo CHtml::hiddenField('UserGroupsAccess[displayname]', ucfirst($name)); ?>
	<?php echo CHtml::submitButton(Yii::t('userGroupsModule.general', 'Save')); ?>
</div>
<?php $this->endWidget(); ?>
<?php if ($id !== 'new' && Yii::app()->user->pbac('userGroups.admin.admin')): ?>
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'user-groups-delete-form-' . $what,
	'enableAjaxValidation'=>false,
	'action'=> Yii::app()->baseUrl .'/userGroups/admin',
)); ?>
<div class="row buttons right-floated">
	<?php echo CHtml::hiddenField('UserGroupsAccess[what]', $what); ?>
	<?php echo CHtml::hiddenField('UserGroupsAccess[id]', $id); ?>
	<?php echo CHtml::hiddenField('UserGroupsAccess[displayname]', ucfirst($name)); ?>
	<?php echo CHtml::hiddenField('UserGroupsAccess[delete]', 'yes'); ?>
	<?php 
	if ((int)$what === UserGroupsAccess::USER)
		$confirm_message = Yii::t('userGroupsModule.admin', 'Do you really want to delete the user {user}?', array('{user}' => ucfirst($name)));
	else {
		$confirm_message = Yii::t('userGroupsModule.admin', 'Do you really want to delete the group {group}?', array('{group}' => ucfirst($name)));
		$confirm_message .= '\n'. Yii::t('userGroupsModule.admin', 'Remember if you delete a Group you\'ll delete all the users that belongs to it.');
	}
		
	?>
	<?php echo CHtml::submitButton(Yii::t('userGroupsModule.general','Delete'), array('onclick' => 'js: if(confirm("'.$confirm_message.'")) {return true;}else{return false;}')); ?>
</div>
<?php $this->endWidget(); ?>
<?php endif; ?>

views/admin/configurations.php
<h1 class="closed" onclick="$(this).toggleClass('opened').nextAll('.hidden-panel').first().slideToggle();"><?php echo Yii::t('userGroupsModule.admin', 'Main Configurations'); ?></h1>
<?php if(Yii::app()->user->hasFlash('configuration')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('configuration'); ?>
    </div>
<?php endif; ?>
<div class="hidden-panel">
	<?php 
	if (Yii::app()->user->pbac('admin.admin')) {
		$form=$this->beginWidget('CActiveForm', array(
			'id'=>'user-groups-admin-form',
			'enableAjaxValidation'=>false,
		));
	}
	?>
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$confDataProvider,
		'id'=>'configuration-list',
		'enableSorting'=>false,
		'summaryText'=>false,
		'selectableRows'=>0,
		'columns'=>array(
			'rule',
			array(
				'name'=>'render',
				'type'=>'raw',
			),
			array(
				'name'=>'description',
				'type'=>'raw',
			), 
		),
	)); ?>
	<?php if (Yii::app()->user->pbac('admin.admin')): ?>
	<div class="row buttons">
		<?php echo CHtml::submitButton('Save'); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php endif; ?>
</div>

views/admin/crons.php
<h1 class="closed" onclick="$(this).toggleClass('opened').next('.hidden-panel').slideToggle();"><?php echo Yii::t('userGroupsModule.admin', 'Cron Jobs'); ?></h1>
<?php if(Yii::app()->user->hasFlash('crons')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('crons'); ?>
    </div>
<?php endif; ?>
<div class="hidden-panel">
	<?php 
	if (Yii::app()->user->pbac('userGroups.admin.admin'))
		$form=$this->beginWidget('CActiveForm', array(
			'id'=>'user-groups-cron-form',
			'enableAjaxValidation'=>false,
		)); 
	?>
	<?php
	// load the cronjobs
	UGCron::init();
	UGCron::add(new UGCJGarbageCollection);
	UGCron::add(new UGCJUnban);
	foreach (Yii::app()->controller->module->crons as $c) {
		UGCron::add(new $c);
	} 
	?>
	<?php $this->widget('zii.widgets.grid.CGridView', array(
		'dataProvider'=>$cronDataProvider,
		'id'=>'configuration-list',
		'enableSorting'=>false,
		'summaryText'=>false,
		'selectableRows'=>0,
		'columns'=>array(
			'name',
			array(
				'name'=>'lapse',
				'value'=> Yii::app()->user->pbac('userGroups.admin.admin') ? 'CHtml::textField("UserGroupsCron[$data->id]", $data->lapse, array("class" => "lapse"))' : '$data->lapse',
				'type'=>'raw',
			),
			array(
				'name'=>'last_occurrence',
				// TODO when stop supporting php 5.2 use strstr
				'value'=>'substr($data->last_occurrence,0,strpos($data->last_occurrence," "))',
			),
			array(
				'name'=>'status',
				'value'=>'UGCron::getStatus($data->name, true, true)',
				'type'=>'raw',
			), 
			array(
				'name'=>'description',
				'value'=>'UGCron::getDescriptions($data->name, true);',
			),
		),
	)); ?>
	<?php if (Yii::app()->user->pbac('userGroups.admin.admin')): ?>
	<div class="inline buttons">
		<?php echo CHtml::submitButton(Yii::t('userGroupsModule.general','Save')); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'user-groups-cron-delete-form-',
		'enableAjaxValidation'=>false,
		'action'=>'/userGroups/admin',
	)); ?>
	<div class="inline buttons">
		<?php echo CHtml::hiddenField('UserGroupsCronRemove[remove]', 'yes'); ?>
		<?php echo CHtml::submitButton(Yii::t('userGroupsModule.admin','Remove not installed CronJobs'), array('onclick' => 'js: if(confirm("'. Yii::t('userGroupsModule.admin', 'Do you really want to remove those CronJobs?').'")) {return true;}else{return false;}')); ?>
	</div>
	<?php $this->endWidget(); ?>
	<?php endif; ?>
</div>

views/admin/documentation.php
<?php
$this->breadcrumbs=array(
	Yii::t('userGroupsModule.general','Documentation'),
);
?>
<div id="userGroups-container">
	<div class="userGroupsMenu-container">
		<?php $this->renderPartial('/admin/menu', array('mode' => 'profile', 'documentation' => true))?>
	</div>

	<?php
	$this->widget('zii.widgets.jui.CJuiAccordion', array(
	    'panels'=>array(
	        Yii::t('userGroupsModule.admin','First Steps') =>$this->renderPartial('documentation/first_steps', null, true),
	        Yii::t('userGroupsModule.admin','Setup the new accessControlFilter') =>$this->renderPartial('documentation/access_rules', null, true),
	        Yii::t('userGroupsModule.admin','Using the new Access Rules') =>$this->renderPartial('documentation/access_rules_2', null, true),
	        Yii::t('userGroupsModule.admin','Root Tools') =>$this->renderPartial('documentation/root_tools', null, true),
	        Yii::t('userGroupsModule.admin','Cron Jobs') =>$this->renderPartial('documentation/cron_jobs', null, true),
	        Yii::t('userGroupsModule.admin','Profile Extensions') =>$this->renderPartial('documentation/profile', null, true),
	        Yii::t('userGroupsModule.admin','Email Customization') =>$this->renderPartial('documentation/email', null, true),
	        Yii::t('userGroupsModule.admin','Localization') =>$this->renderPartial('documentation/localization', null, true),
	        Yii::t('userGroupsModule.admin','Is this thing safe?') =>$this->renderPartial('documentation/is_safe', null, true),
	        Yii::t('userGroupsModule.admin','What\'s new?') =>$this->renderPartial('documentation/new', null, true),
	        Yii::t('userGroupsModule.admin','What\'s coming next?') =>$this->renderPartial('documentation/next', null, true),
	        Yii::t('userGroupsModule.admin','License') =>$this->renderPartial('documentation/license', null, true),
	        Yii::t('userGroupsModule.admin','About the author') =>$this->renderPartial('documentation/about_me', null, true),
	        // panel 3 contains the content rendered by a partial view
	        //'panel 3'=>$this->renderPartial('_partial',null,true),
	    ),
	    // additional javascript options for the accordion plugin
	    'options'=>array(
	        'animated'=>'bounceslide',
	    	#'fillSpace'=>true,
	    	'autoHeight'=>false,
	    	'navigation'=>true,
	    ),
	    'htmlOptions'=>array(
	    	'id'=>'documentation-accordion',
	    ),
	));
	?>
	<script>
	$('#documentation-accordion').bind('accordionchange', function(event, ui) {
		if ($('html').scrollTop() > ui.newHeader.offset().top) {
			$('html, body').animate({
				scrollTop: ui.newHeader.offset().top
			}, 1000);
		}
	});
	</script>
</div>

views/admin/groups.php
<h1><?php echo Yii::t('userGroupsModule.general', 'Groups'); ?></h1>
<?php if(Yii::app()->user->hasFlash('group')):?>
    <div class="info">
        <?php echo Yii::app()->user->getFlash('group'); ?>
    </div>
<?php endif; ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$groupModel->search(),
	'id'=>'user-groups-group-grid',
	'enableSorting'=>false,
	'filter'=>$groupModel,
	'summaryText'=>false,
	'selectionChanged'=> 'function(id) { getPermission("'.Yii::app()->baseUrl.'", "'.UserGroupsAccess::GROUP.'", $.fn.yiiGridView.getSelection(id))}',
	'columns'=>array(
		'groupname',
		'level',
	),
)); ?>
<?php
if (Yii::app()->user->pbac('userGroups.admin.admin'))
	echo CHtml::ajaxLink(Yii::t('userGroupsModule.admin', 'add group'), 
	Yii::app()->createUrl('/userGroups/admin/accessList', array('what'=>UserGroupsAccess::GROUP, 'id'=>'new')), 
	array('success'=>'js: function(data){ $("#group-detail").slideUp("slow", function(){ $("#group-detail").html(data).slideDown();}); }'),
	array('id'=>'new-group-'.time()));
?>
<div id="group-detail" style="display:none;"></div>

views/admin/menu.php
<?php

$userGroupsMenu = array();

if ($mode === 'profile') {
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','My Profile'), 'url'=>array('/userGroups'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
	if (isset($username))
		$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','{username}\'s Profile',array('{username}'=>$username)), 'url'=>array('/userGroups?u='.$username), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
} else if ($mode === 'edit')
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Edit Profile'), 'url'=>array('user/update', 'id'=>Yii::app()->user->id), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
else if ($mode === 'admin') {
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','My Profile'), 'url'=>array('/userGroups'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
	$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Edit {username}\'s Profile', array('{username}'=>$username)), 'url'=>array('user/update', 'id'=>$id), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => !Yii::app()->user->isGuest);
}

$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','Invite User'), 'url'=>array('user/invite'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('user.admin', 'admin.admin')), 'active' => isset($invite));
$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.general','User List'), 'url'=>array('user/index'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('user.admin', 'admin.admin'), 'public_user_list', 'OR'), 'active' => isset($list));
$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.admin','Root Tools'), 'url'=>array('admin/'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac(array('admin.write', 'admin.admin')), 'active' => isset($root));
$userGroupsMenu[] = array('label'=>Yii::t('userGroupsModule.admin','Documentation'), 'url'=>array('admin/documentation'), 'linkOptions'=> array('onclick' => 'js: return loadPage(this)'), 'visible' => Yii::app()->user->pbac('admin.read'), 'active' => isset($documentation));

$this->widget('zii.widgets.CMenu', array(
	'items'=>$userGroupsMenu,
	'htmlOptions'=>array('class'=>'userGroupsMenu'),
	'lastItemCssClass' => 'last',
));